### ISSUE TITLE
sign in 

### ISSUE THREAD

**Issue by thasebe** [MicrosoftDocs/Azure-RMSDocs.ja-jp#21]
sign in わかりにくい

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1562feec-bf8f-9e84-b642-bcd259c8a418
* Version Independent ID: 953ab73d-8ee8-b63e-a7d4-52aaa60026f8
* Content: [iOS 用と Android 用の Azure Information Protection アプリに関する FAQ](https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/mobile-app-faq)
* Content Source: [Azure-RMSDocs/rms-client/mobile-app-faq.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/blob/live/Azure-RMSDocs/rms-client/mobile-app-faq.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by CeciAc** [comment]
@thasebe  様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
@thasebe 様、
先にお送りしたコメントについてさらにお知らせいたします。お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
@thasebe 様、
再度コメントをいただき、ありがとうございます。
大変申し訳ございませんが、いただいたフィードバックを処理するには、依然として情報が不足しております。この度いただいた GitHub の問題はここで終了とさせていただきますが、今後とも、さらにフィードバックをお寄せいただきますよう、お願い申し上げます。
敬具
Microsoft DOCS インターナショナル チーム
