### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by nhirose17** [MicrosoftDocs/Azure-RMSDocs.ja-jp#23]
In the following sentence, [公開] should be [分類] .

Office ドキュメントにこれらの分類の値のいずれかのラベルを付けるには、 [SyncPropertyName] を [公開] に、 [SyncPropertyState] を [OneWay] に設定します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 08ae0fec-f7a5-e963-b304-f55755cfd3db
* Version Independent ID: bfed1edd-3fee-0ea1-b478-ddcc76e2adc3
* Content: [カスタム構成-Azure Information Protection クライアント](https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/client-admin-guide-customizations#feedback)
* Content Source: [Azure-RMSDocs/rms-client/client-admin-guide-customizations.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/blob/live/Azure-RMSDocs/rms-client/client-admin-guide-customizations.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by srvbpigh** [comment]
Hello, @nhirose17
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @nhirose17
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/client-admin-guide-customizations#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team

**Comment by nhirose17** [comment]
Hello,
I appreciate your prompt actions. I checked the web page and confirmed that it has been corrected. Thank you!
________________________________
差出人: Cecilia Acevedo <notifications@github.com>
送信日r: 2019年7月25日 21:21
宛先: MicrosoftDocs/Azure-RMSDocs.ja-jp <Azure-RMSDocs.ja-jp@noreply.github.com>
CC: nhirose17 <nhirose17@outlook.com>; Mention <mention@noreply.github.com>
件名: Re: [MicrosoftDocs/Azure-RMSDocs.ja-jp] Translation error (#23)


Hello, @nhirose17<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnhirose17&data=02%7C01%7C%7C8ef0c85b339c41bf9d4308d711461b01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996865099976903&sdata=ZlDfcr%2ByhYeXARU7G%2BO4YZdjeGR94wUtF4AdU0LE8zc%3D&reserved=0>

Thank you for your feedback.

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/client-admin-guide-customizations#feedback<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fja-jp%2Fazure%2Finformation-protection%2Frms-client%2Fclient-admin-guide-customizations%23feedback&data=02%7C01%7C%7C8ef0c85b339c41bf9d4308d711461b01%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636996865099987186&sdata=gjfi%2BEljnEE%2Be4JjvPvNruCODhLD5JQi6x1fpSDlX9A%3D&reserved=0>

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

―
