### ISSUE TITLE
機械翻訳による誤訳？を修正して欲しい

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/Azure-RMSDocs.ja-jp#24]
バージョン1.48.204.0について
02/15/2020 でサポート
とあるが、実際は「02/15/2020 までサポート」を意味するかと認識しております。

修正をお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 28d40811-9908-39df-a632-a31be13d9ad9
* Version Independent ID: b5c3157d-20d1-57d3-5332-41e385ebd7b9
* Content: [Azure Information Protection クライアント-バージョン履歴 & サポートポリシー](https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/client-version-release-history#version-1482040)
* Content Source: [Azure-RMSDocs/rms-client/client-version-release-history.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/blob/live/Azure-RMSDocs/rms-client/client-version-release-history.md)
* Service: **information-protection**
* GitHub Login: @cabailey
* Microsoft Alias: **cabailey**

**Comment by srvbpigh** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/client-version-release-history#version-1482040

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
