### ISSUE TITLE
比較テーブルの誤訳修正依頼

### ISSUE THREAD

**Issue by gihayash** [MicrosoftDocs/Azure-RMSDocs.ja-jp#29]
[フィードバックをこちらに入力してください]
Windows コンピューターのラベル付けクライアントの比較 にて
Yes に対する訳として、「はい」・「うん」・「可」の種類があり、混乱を生じているため、記載を統一して頂きたい。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f3a13e85-78dd-d4e0-30d9-4acc40f3e11a
* Version Independent ID: 09429982-159f-81fd-a989-901142dee148
* Content: [Azure Information Protection のクライアント](https://docs.microsoft.com/ja-jp/azure/information-protection/rms-client/use-client#compare-the-labeling-clients-for-windows-computers)
* Content Source: [Azure-RMSDocs/rms-client/use-client.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/blob/live/Azure-RMSDocs/rms-client/use-client.md)
* Service: **information-protection**
* GitHub Login: @mlottner
* Microsoft Alias: **mlottner**

**Comment by srvbpigh** [comment]
Hello, @gihayash
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
@gihayash 様: 

投稿いただき、ありがとうございます。 

現在、機械翻訳されたコンテンツに対する翻訳の問題へのコントリビューションはできません。 

人間が翻訳したコンテンツに関するフィードバックやご意見をお寄せください。人間が翻訳したコンテンツは機械翻訳エンジンをトレーニングするために使用されているため、お客様は、時間が経つにつれ人間および機械の両方による翻訳の質を向上させることに貢献できます。 

人間が翻訳したトピックは、各コンテンツ ファイルのヘッダーの translationtype メタデータ値 "HT" (機械翻訳の場合は "MT") によって、機械翻訳されたトピックと区別できます。 

サポートいただきありがとうございます。 

Microsoft DOCS グローバル エクスペリエンス チーム
