### ISSUE TITLE
Add to the TLS communication specification. Versions of .NET Framework 4.6.1 and earlier use TLS 1.0 on the RMS connector in the default configuration.

### ISSUE THREAD

**Issue by juhirao** [MicrosoftDocs/Azure-RMSDocs.ja-jp#36]
[フィードバックをこちらに入力してください]
Depending on the version configuration of the .Net Framework of the operating system installed in the RMS Connector, TLS communication is performed to the Azure RMS service using TLS 1.0/1.1.
The overall roadmap for Office 365 is deprecating TLS 1.0/1.1, but the RMS connector uses TLS 1.0/1.1, for example, in environments operating with Windows Server 2012 R2, where .NET Framework version 4.6.1 or lower is the default version.
A number of RMS connector-related failures occurred last November when there was a change on the Azure RMS side to disable TLS 1.0/1.1.
It is now back to the original Azure RMS service instance and TLS 1.0/1.1 is in effect.

When there was a change to disable TLS 1.0/1.1 on the Azure RMS side last November, a number of RMS connector-related failures occurred and are now back to the original instance.
Upgrading the .NET Framework to a 4.6.2 or later version or adjusting registry settings will result in tls 1.2 being used to avoid problems during the next TLS 1.0/1.1 deprecation of azure RMS services.
As a prerequisite for the RMS connector, you should add that the RMS connector needs to update the .NET Framework or set up the registry to use TLS 1.2.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 98397d63-e9a3-a620-9efc-bfd3371a3c61
* Version Independent ID: 652e8b33-90e0-aad6-3238-fc8b41eda674
* Content: [Rights Management コネクタのインストールと構成 - AIP](https://docs.microsoft.com/ja-jp/azure/information-protection/install-configure-rms-connector)
* Content Source: [Azure-RMSDocs/install-configure-rms-connector.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/blob/live/Azure-RMSDocs/install-configure-rms-connector.md)
* Service: **information-protection**
* Sub-service: **connector**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @juhirao - thank you for taking the time to send us your suggestion!

We're in the process of working through some related feedback, and I'll confirm this change with the team as part of that effort. 

I'm closing this in the meantime, but feel free to continue to comment here as needed.
#please-close
