### ISSUE TITLE
Japanese translation issue

### ISSUE THREAD

**Issue by TadaoMachida** [MicrosoftDocs/Azure-RMSDocs.ja-jp#37]
In this section,
https://docs.microsoft.com/ja-jp/azure/information-protection/activate-service#automatic-activation-for-azure-rights-management

"Azure Information Protection was obtained towards the end of February 2018 or later." is translated as "Azure Information Protection が含まれているサブスクリプションが2018年2月以降の終了日に取得された場合". This Japanese translation is completely opposite meaning. It means "Azure Information Protection was obtained after February 2018".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1f1e91b8-4dcb-d53f-b07a-05f2c47a636c
* Version Independent ID: 5ae10df9-4624-8f25-7c85-bf717a18f323
* Content: [Azure Information Protection (AIP) からの保護サービスのアクティブ化](https://docs.microsoft.com/ja-jp/azure/information-protection/activate-service#automatic-activation-for-azure-rights-management)
* Content Source: [Azure-RMSDocs/activate-service.md](https://github.com/MicrosoftDocs/Azure-RMSDocs.ja-jp/blob/live/Azure-RMSDocs/activate-service.md)
* Service: **information-protection**
* Sub-service: **azurerms**
* GitHub Login: @batamig
* Microsoft Alias: **bagol**

**Comment by batamig** [comment]
Hi @TadaoMachida and thanks for this important feedback! I've notified the relevant focal point for this translation and it will be updated as needed in a coming fix.
I'm closing this issue for now, but feel free to comment more if you have additional feedback.

Tagging @JasonCard as the focal point for this translation issue. Thanks!

#please-close

**Comment by JasonCard** [comment]
@TadaoMachida @batamig Thank you for reporting this issue and bringing it to my attention. I'm following up on getting this translation fixed.

**Comment by JasonCard** [comment]
@TadaoMachida @batamig This issue is now fixed. Both of the sentences below were fixed:
- Azure Rights Management または Azure Information Protection を含むサブスクリプションを 2018 年 2 月末日以降を対象として取得した場合
- Azure Rights Management または Azure Information Protection を含むサブスクリプションを 2018 年 2 月以前に取得した場合
Please let me know if you have any further feedback.

**Comment by batamig** [comment]
@JasonCard thank you so much for handling and also following up!
